# Author: Zakaria Kebairia
# Email: 4.kebairia@gmail.com
#
# This Github actions workflow publishes the generated site to Github pages.
#

name: Publish site to GitHub Pages

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  publish:
    # Run the job on an Ubuntu 22.04 virtual machine
    runs-on: ubuntu-22.04
    
    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install git to commit and push changes
      - name: Install Git
        run: sudo apt install git -y

      # Install Emacs to use with the build process
      - name: Install Emacs text editor (nox version)
        run: sudo apt install emacs-nox --yes

      # Update the file modification timestamps for org files
      - name: Update Org file timestamps
        run: bash ./update_org_file_timestamps.sh

      # Build the site using the build script
      - name: Build site using build script
        run: ./build.sh

      # Deploy the generated site to Github Pages using JamesIves/github-pages-deploy-action
      - name: Deploy site to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # Deploy to the gh-pages branch
          branch: gh-pages
          # Deploy the content from the public directory
          folder: public
